package com.ejbank.exception;

public enum ErrorIdentifier {
    USER_NOT_FOUND,
    USER_IS_NOT_A_CUSTOMER,
    ACCOUNT_NOT_ASSIGNED_TO_ADVISOR,
    ACCOUNT_NOT_FOUND, CUSTOMER_NOT_FOUND, ACCOUNT_NOT_ASSIGNED_TO_CUSTOMER
}
