package com.ejbank.exception;

public enum ErrorIdentifier {
    USER_NOT_FOUND,
    USER_IS_NOT_A_CUSTOMER,
    ACCOUNT_NOT_ASSIGNED_TO_ADVISOR,
    ACCOUNT_NOT_FOUND, CUSTOMER_NOT_FOUND, SOURCE_ACCOUNT_NOT_FOUND, DESTINATION_ACCOUNT_NOT_FOUND, TRANSACTION_NOT_FOUND, TECHNICAL_ERROR, TRANSACTION_REFUSED, AUTHOR_IS_NOT_CORRECT, ACCOUNT_NOT_ASSIGNED_TO_CUSTOMER
}
